name: RSVP monitor

on:
  schedule:
    - cron: '0 * * * *'        # every hour, UTC  :contentReference[oaicite:3]{index=3}
  workflow_dispatch:           # manual “Run workflow” button

jobs:
  scrape:
    runs-on: ubuntu-latest     # free GitHub runner  :contentReference[oaicite:4]{index=4}
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}   # << add this secret
    steps:
      - uses: actions/checkout@v4                       # pulls code  :contentReference[oaicite:5]{index=5}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'                                  # pip cache  :contentReference[oaicite:6]{index=6}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download last snapshot
        uses: actions/download-artifact@v4
        with:
          name: snapshot
          path: .
          if-no-files-found: ignore 
      - name: Run monitor
        run: python rsvp_monitor.py
      - name: Upload new snapshot
        uses: actions/upload-artifact@v4
        with:
          name: snapshot
          path: previous_products.json
          retention-days: 90
