name: RSVP monitor          # appears in the Actions tab

on:
  schedule:                 # cron times are always interpreted in UTC :contentReference[oaicite:0]{index=0}
    - cron: '0 * * * *'     # run at the top of every hour
  workflow_dispatch:        # lets you click “Run workflow” for a manual test :contentReference[oaicite:1]{index=1}

jobs:
  scrape:
    runs-on: ubuntu-latest  # free GitHub-hosted runner tier :contentReference[oaicite:2]{index=2}
    env:                    # expose your secret to the script as an env var :contentReference[oaicite:3]{index=3}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - uses: actions/checkout@v4    # fetch your repo contents :contentReference[oaicite:4]{index=4}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'     # pick any version pre-cached on the runner :contentReference[oaicite:5]{index=5}
          cache: 'pip'               # built-in dependency caching for pip :contentReference[oaicite:6]{index=6}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run monitor
        run: |
          python rsvp_monitor.py
